INSERT INTO CATEGORY (ID, NAME, VERSION) VALUES (1,'cat', 0);
INSERT INTO CATEGORY (ID, NAME, VERSION) VALUES (2,'dog', 0);

INSERT INTO PET (ID, NAME, CATEGORY_ID, PHOTO_URLS, STATUS, VERSION) VALUES (1, 'King Charles Spaniel', 2,  '', 'AVAILABLE', 0);


